### ISSUE TITLE
Version 2.0 : Format date not valid when validating contract

### ISSUE THREAD

**Issue by KilianStein** [Bonitasoft-Community/restapi_context#1]
Hello,
Thx for this hard work.

I found a bug with the version 2.0, i know that it's not release yet but i want to give you quick feedback.

I have a attribut Date in my BDM. The format return with restapi_context is "aDate":"2016-04-27T22:39:32+0000" which it's not valid with bonita contract (date) : "2016-04-27T22:39:32+0000 cannot be assigned to DATE"

Angular use this format : "aDate":"2016-04-27T22:39:32.000Z"

**Comment by pierre-yves-monnet** [comment]
Thanks for this comment on the pre release ! And sorry about that, I will fix it (maybe not so easy because in fact I send what the BDM return, but I will parse and transform the date, good point).

The source is on the Github : download ContextAccess.2.0.bos, and load it on a studio. Then on Developement, access the RestApi Extension : you have it.
I keep the same format as the Bonita Studio extends, except to unzip and save all information, but it's an interresting point to accept and track the modification on Github. So, I think I will do this way. I'll try.
