### ISSUE TITLE
Error on Deployment

### ISSUE THREAD

**Issue by PhilippHeuer** [Bonitasoft-Community/restapi_context#5]
The Extension doesn't work, since the upload is not possible.

Bonita Subscription: 7.1 on Windows.

Error:
2016-12-01 11:40:24.095 +0100 org.bonitasoft.console.common.server.servlet.PageUploadServlet org.bonitasoft.console.common.server.servlet.PageUploadServlet getPermissionsError 
WARNUNG: USERNAME=Walter.Bates | Missing Index.groovy or index.html

**Comment by pierre-yves-monnet** [comment]
Hello Philipp,
This is because the REST API structure change between 7.1 and 7.2 and after.
To let the REST API to be deploy in 7.1 :
1/ unzip the REST API CONTEXT in a directory
2/ add a Index.groovy file. You can find on in the "rest api example". In the portal, "export" it and unzip it.
3/ change the import : the RestApiController class was in a different package. So found the "GetContext.groovy" and change that inside.

// import org.bonitasoft.web.extension.rest.RestApiController;
// import org.bonitasoft.web.extension.rest.RestAPIContext;

import org.bonitasoft.console.common.server.page.*

4/ zip the file. Then you can deploy it. I didn't test it.
